name: Deploy to GitHub Pages

# deploy from master
on:
  push:
    branches: main
    
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      # clone repo to vm
    - uses: actions/checkout@v2
    
      # install dependencies
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
        include-prerelease: true
        
      # publish static
    - name: Publish .NET Core Project
      working-directory: src/ProjectFabric.Blazor.Wasm
      run: dotnet publish -c Release --output release --nologo
      
      # deploy to Github Pages 
    - name: Uploading files to gh-pages branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: src/ProjectFabric.Blazor.Wasm/release/wwwroot
        ssh-key: ${{ secrets.DEPLOY_KEY }}

     # change'/' to '/projectfabric/'
    - name: Change base-tag in index.html from / to projectfabric
      run: sed -i 's/<base href="\/" \/>/<base href="\/projectfabric\/" \/>/g' release/wwwroot/index.html
      
     # disable jekyll
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll